language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: ITKnfNABeQ47DbDKibSv5SQMzBOQkLYTAWMmcNU+Cga4HK8p2zNy5CrhLm4B2B3YBXDRIcazd2L+wliep25lm/b9nFoBAclNsLqI8xyHDeTz1HkPyscPVLYc8sYzkhWzyrvX7ye+58rR9XVIiRjFofqZPkroEDbo5PfQQ20EqK3xrEDSR2bpYcrbEVdMSIGuouSrZcCu/H9mPZ6+6ycP+5AB9dFg5TNZouBVDhnxMdkgQeE4+cnXlGJb+i167n7xJRHQRDO89YQTXFAmEup+9gv7Qi+kBDXZPWjv/YUvGKyHND5KwiyZg7jBpBWgRexJB25/TfgXZTw748i6ObrrtKbviG8EIRV0YZt1mU3YIpvHu18KwSXMUT8HAT9HbGrsOtSylYOQ/IXOvdXgjIJVQdCTZDF/TIrOHYQdahzkdB4b4DS869tOf5WHRTt9WLs8FLO8m/t9dUT83aMhMJxOVT+g2M7urw5aOIEcd0UGiBO/pGhnQariwpOtHHPES3sQ6g+4AEmrQqv3mSmhzJEQkWaTJuB86TmhQpf6wNHrzPVTltT++PKLzf5pXFPKM+mOhzLHoZYY53t41xYV4dSpBFw9V5Aw/v3hv7pJyDCf+rtv8jU9OLPxUgtaVBp699+SDI12/Y7sV3aIBkVo4f44Vmfkl8pqXnjxSHrSoISHhpY=
  - secure: Y4OEsevfZFmUlD0B4gXFNZcZrSOoxTl7S9Az8cg7AZD1S3195oYJUcBnqXuYPo+Jt9nAE9MosVHbW7H9wyZvStmtIk+cG3yES57fRXkK6UXXeRdnm3aEZ+to2AkdZcr/fnG4RymPYG4Ma9i2m14DYgFylh8Flzo05w/nBek9AMYMREyNXj2UdbFuLQmMsUT3Bxb2jeG2qrf/Q3kVzkAPfZYwR/f6QA8BspI8Ee4KF+ivwyNldZ+oWwLZz36Xw6BfsYZtdj85CfI0OYW5c9BvE81K6+mUrR3yKKW+5kDyjdHLUlBor5ift9FzeiZ+pHECsuq2dhR6KlUkXbwFkI9qNzMB9vYBrzqZbbpXvVWh05zwnHPE05NX0JYbIMhFzR+rHGaGjnSdXdDLbqSIx2G9xDLMFOrA1J6kqejIWBeCNTezKT72AlUPMsSS3IyVAPACJe6Yc1HusLBH0tSA+MV1Yfj4sl9npVoKj9N7eqvjySh0YfvH3BbheCYi1ycdff6es0X7SZcHtIVfyXNFJQ+jRLTjhy+JX29zP5JYXEceGXClkHjSpOkrAHOWLAeoYCwZQOM47TWxKhq+6OX6L3gnKRXzXiBlfk2eQuUEFasI3VCWx17pxrfxAnqB21w/tYoRZf1S9M0OYp6EMeLesBKjQuyweN1J79ZacylpI8+QQyg=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
